RestoManagerMehdi/Models/RestosModel/Restaurant.cs
namespace RestoManagerMehdi.Models.RestosModel
{
    public class Restaurant
    {
        public int CodeResto { get; set; }
        public string NomResto { get; set; } = null!;
        public string Specialite { get; set; } = null!;
        public string Ville { get; set; } = null!;
        public string Tel { get; set; } = null!;
        public int NumProp { get; set; }
        public virtual Proprietaire? LeProprio { get; set; }
        public virtual ICollection<Avis>? LesAvis { get; set; }
    }
}

RestoManagerMehdi/Controllers/AvisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RestoManagerMehdi.Models.RestosModel;

namespace RestoManagerMehdi.Controllers
{
    public class AvisController : Controller
    {
        private readonly RestosDbContext _context;

        public AvisController(RestosDbContext context)
        {
            _context = context;
        }

        // GET: Avis
        public async Task<IActionResult> Index()
        {
            var restosDbContext = _context.Avis.Include(a => a.LeResto);
            return View(await restosDbContext.ToListAsync());
        }

        // GET: Avis/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Avis == null)
            {
                return NotFound();
            }

            var avis = await _context.Avis
                .Include(a => a.LeResto)
                .FirstOrDefaultAsync(m => m.CodeAvis == id);
            if (avis == null)
            {
                return NotFound();
            }

            return View(avis);
        }

        // GET: Avis/Create
        public IActionResult Create()
        {
            ViewData["NumResto"] = new SelectList(_context.Restaurants, "CodeResto", "Specialite");
            return View();
        }

        // POST: Avis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CodeAvis,NomPersonne,Note,Commentaire,NumResto")] Avis avis)
        {
        //    if (ModelState.IsValid)
            {
                _context.Add(avis);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["NumResto"] = new SelectList(_context.Restaurants, "CodeResto", "Specialite", avis.NumResto);
            return View(avis);
        }

        // GET: Avis/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Avis == null)
            {
                return NotFound();
            }

            var avis = await _context.Avis.FindAsync(id);
            if (avis == null)
            {
                return NotFound();
            }
            ViewData["NumResto"] = new SelectList(_context.Restaurants, "CodeResto", "Specialite", avis.NumResto);
            return View(avis);
        }

        // POST: Avis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CodeAvis,NomPersonne,Note,Commentaire,NumResto")] Avis avis)
        {
            if (id != avis.CodeAvis)
            {
                return NotFound();
            }

          //  if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(avis);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AvisExists(avis.CodeAvis))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["NumResto"] = new SelectList(_context.Restaurants, "CodeResto", "Specialite", avis.NumResto);
            return View(avis);
        }

        // GET: Avis/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Avis == null)
            {
                return NotFound();
            }

            var avis = await _context.Avis
                .Include(a => a.LeResto)
                .FirstOrDefaultAsync(m => m.CodeAvis == id);
            if (avis == null)
            {
                return NotFound();
            }

            return View(avis);
        }

        // POST: Avis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Avis == null)
            {
                return Problem("Entity set 'RestosDbContext.Avis'  is null.");
            }
            var avis = await _context.Avis.FindAsync(id);
            if (avis != null)
            {
                _context.Avis.Remove(avis);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AvisExists(int id)
        {
          return (_context.Avis?.Any(e => e.CodeAvis == id)).GetValueOrDefault();
        }
    }
}

RestoManagerMehdi/Controllers/ProprietairesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RestoManagerMehdi.Models.RestosModel;

namespace RestoManagerMehdi.Controllers
{
    public class ProprietairesController : Controller
    {
        private readonly RestosDbContext _context;

        public ProprietairesController(RestosDbContext context)
        {
            _context = context;
        }

        // GET: Proprietaires
        public async Task<IActionResult> Index()
        {
              return _context.Proprietaires != null ? 
                          View(await _context.Proprietaires.ToListAsync()) :
                          Problem("Entity set 'RestosDbContext.Proprietaires'  is null.");
        }

        // GET: Proprietaires/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Proprietaires == null)
            {
                return NotFound();
            }

            var proprietaire = await _context.Proprietaires
                .FirstOrDefaultAsync(m => m.Numero == id);
            if (proprietaire == null)
            {
                return NotFound();
            }

            return View(proprietaire);
        }

        // GET: Proprietaires/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Proprietaires/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Numero,Nom,Email,Gsm")] Proprietaire proprietaire)
        {
            if (ModelState.IsValid)
            {
                _context.Add(proprietaire);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(proprietaire);
        }

        // GET: Proprietaires/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Proprietaires == null)
            {
                return NotFound();
            }

            var proprietaire = await _context.Proprietaires.FindAsync(id);
            if (proprietaire == null)
            {
                return NotFound();
            }
            return View(proprietaire);
        }

        // POST: Proprietaires/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Numero,Nom,Email,Gsm")] Proprietaire proprietaire)
        {
            if (id != proprietaire.Numero)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(proprietaire);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProprietaireExists(proprietaire.Numero))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(proprietaire);
        }

        // GET: Proprietaires/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Proprietaires == null)
            {
                return NotFound();
            }

            var proprietaire = await _context.Proprietaires
                .FirstOrDefaultAsync(m => m.Numero == id);
            if (proprietaire == null)
            {
                return NotFound();
            }

            return View(proprietaire);
        }

        // POST: Proprietaires/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Proprietaires == null)
            {
                return Problem("Entity set 'RestosDbContext.Proprietaires'  is null.");
            }
            var proprietaire = await _context.Proprietaires.FindAsync(id);
            if (proprietaire != null)
            {
                _context.Proprietaires.Remove(proprietaire);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProprietaireExists(int id)
        {
          return (_context.Proprietaires?.Any(e => e.Numero == id)).GetValueOrDefault();
        }
    }
}

RestoManagerMehdi/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RestoManagerMehdi.Models.RestosModel;

namespace RestoManagerMehdi.Controllers
{
    public class RestaurantsController : Controller
    {
        private readonly RestosDbContext _context;

        public RestaurantsController(RestosDbContext context)
        {
            _context = context;
        }

        // GET: Restaurants
        public async Task<IActionResult> Index()
        {
            var restosDbContext = _context.Restaurants.Include(r => r.LeProprio);
            return View(await restosDbContext.ToListAsync());
        }

        // GET: Restaurants/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Restaurants == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurants
                .Include(r => r.LeProprio)
                .FirstOrDefaultAsync(m => m.CodeResto == id);
            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }

        // GET: Restaurants/Create
        public IActionResult Create()
        {
            ViewData["NumProp"] = new SelectList(_context.Proprietaires, "Numero", "Email");
            return View();
        }

        // POST: Restaurants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CodeResto,NomResto,Specialite,Ville,Tel,NumProp")] Restaurant restaurant)
        {
         //   if (ModelState.IsValid)
            {
                _context.Add(restaurant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["NumProp"] = new SelectList(_context.Proprietaires, "Numero", "Email", restaurant.NumProp);
            return View(restaurant);
        }

        // GET: Restaurants/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Restaurants == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurants.FindAsync(id);
            if (restaurant == null)
            {
                return NotFound();
            }
            ViewData["NumProp"] = new SelectList(_context.Proprietaires, "Numero", "Email", restaurant.NumProp);
            return View(restaurant);
        }

        // POST: Restaurants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CodeResto,NomResto,Specialite,Ville,Tel,NumProp")] Restaurant restaurant)
        {
            if (id != restaurant.CodeResto)
            {
                return NotFound();
            }

          //  if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(restaurant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RestaurantExists(restaurant.CodeResto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["NumProp"] = new SelectList(_context.Proprietaires, "Numero", "Email", restaurant.NumProp);
            return View(restaurant);
        }

        // GET: Restaurants/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Restaurants == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurants
                .Include(r => r.LeProprio)
                .FirstOrDefaultAsync(m => m.CodeResto == id);
            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }

        // POST: Restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Restaurants == null)
            {
                return Problem("Entity set 'RestosDbContext.Restaurants'  is null.");
            }
            var restaurant = await _context.Restaurants.FindAsync(id);
            if (restaurant != null)
            {
                _context.Restaurants.Remove(restaurant);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RestaurantExists(int id)
        {
          return (_context.Restaurants?.Any(e => e.CodeResto == id)).GetValueOrDefault();
        }
    }
}

RestoManagerMehdi/Views/Restaurants/Create.cshtml
@model RestoManagerMehdi.Models.RestosModel.Restaurant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomResto" class="control-label"></label>
                <input asp-for="NomResto" class="form-control" />
                <span asp-validation-for="NomResto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ville" class="control-label"></label>
                <input asp-for="Ville" class="form-control" />
                <span asp-validation-for="Ville" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumProp" class="control-label"></label>
                <select asp-for="NumProp" class ="form-control" asp-items="ViewBag.NumProp"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RestoManagerMehdi/Views/Restaurants/Delete.cshtml
@model RestoManagerMehdi.Models.RestosModel.Restaurant

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomResto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomResto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Specialite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Specialite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ville)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ville)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeProprio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeProprio.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CodeResto" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RestoManagerMehdi/Views/Restaurants/Details.cshtml
@model RestoManagerMehdi.Models.RestosModel.Restaurant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NomResto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NomResto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Specialite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Specialite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ville)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ville)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeProprio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeProprio.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CodeResto">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RestoManagerMehdi/Views/Restaurants/Edit.cshtml
@model RestoManagerMehdi.Models.RestosModel.Restaurant

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CodeResto" />
            <div class="form-group">
                <label asp-for="NomResto" class="control-label"></label>
                <input asp-for="NomResto" class="form-control" />
                <span asp-validation-for="NomResto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Specialite" class="control-label"></label>
                <input asp-for="Specialite" class="form-control" />
                <span asp-validation-for="Specialite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ville" class="control-label"></label>
                <input asp-for="Ville" class="form-control" />
                <span asp-validation-for="Ville" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumProp" class="control-label"></label>
                <select asp-for="NumProp" class="form-control" asp-items="ViewBag.NumProp"></select>
                <span asp-validation-for="NumProp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RestoManagerMehdi/Views/Restaurants/Index.cshtml
@model IEnumerable<RestoManagerMehdi.Models.RestosModel.Restaurant>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomResto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Specialite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ville)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeProprio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NomResto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Specialite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ville)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LeProprio.Email)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.CodeResto">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.CodeResto">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.CodeResto">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<p>
    <div><a asp-action="Index" asp-controller="Avis">Passer a Avis </a></div>
    <div> <a asp-action="Index" asp-controller="Proprietaires">Passer a Prop </a></div>
</p>